### ISSUE TITLE
Error on Search

### ISSUE THREAD

**Issue by machbio** [spinscale/alfred-workflow-elastic-docs#3]
```
[2017-08-08 17:50:21][ERROR: input.scriptfilter] Code 1: {
	"items": [
		{
			"title": "RequestError\n    at ClientRequest.req.once.err (/Users/Username/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.336418F6-08C5-4C17-BEAD-908D1FE37DBD/node_modules/got/index.js:73:21)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at ClientRequest.emit (events.js:210:7)\n    at TLSSocket.socketErrorListener (_http_client.js:401:9)\n    at emitOne (events.js:115:13)\n    at TLSSocket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)",
			"subtitle": "Press ⌘L to see the full error and ⌘C to copy it.",
			"valid": false,
			"text": {
				"copy": "```\nRequestError\n    at ClientRequest.req.once.err (/Users/Username/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.336418F6-08C5-4C17-BEAD-908D1FE37DBD/node_modules/got/index.js:73:21)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)\n```\n\n-\nelastic 1.0\nAlfred 3.4.1\ndarwin x64 16.7.0",
				"largetype": "RequestError\n    at ClientRequest.req.once.err (/Users/Username/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.336418F6-08C5-4C17-BEAD-908D1FE37DBD/node_modules/got/index.js:73:21)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"
			},
			"icon": {
				"path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"
			}
		}
	]
}
```

**Comment by spinscale** [comment]
This looks like a temporary SSL issue. If it is not temporary there may be issues with your firewall/corporate security setup that plays tricks on SSL. Does this still happen with the latest version?
